---

- name: "Starting swarm workers"
  shell: >
        docker swarm join \
          --token {{ hostvars['<%= appName %>-manager1']['worker_token'] }} \
          {{ manager_ip }}:{{ swarm_bind_port }}
  register: init_result
