---
- name: Deploy elk
  hosts: <%= appName %>_managers[0]
  become: yes
  become_user: root
  vars:
    <%= appName %>_home: /opt/<%= appName %>
    manager_ip: <%= defaultIp %>.21
  roles:
    - <%= appName %>-elk