---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarqube
  labels:
    name: sonarqube
  namespace: <%= appName %>
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: mitosis/sonarqube:1.0.0-alpha.0
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    name: sonarqube
  namespace: <%= appName %>
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 9000
    targetPort: 9000
    nodePort: 30002
  selector: