- hosts: <%= appName %>_managers[0]
  name: "** <%= appName %> registry base **"
  gather_facts: false
  become: yes
  become_user: root
  serial: 1
  vars:
    <%= appName %>_home: /opt/<%= appName %>
    manager_ip: <%= defaultIp %>.21
  tasks:

<% if (caasMode === 'swarm' && tools.indexOf("registry") > -1) { %>
  - name: Create local registry
    run_once: true
    shell: >
         docker service create \
           --name registry \
           --label traefik.port=5000 \
           --label traefik.frontend.rule=Host:registry.<%= appName %> \
           -p 5000:5000/tcp \
           --network <%= appName %>-net \
           --mode global \
           registry:2
<% } %>
<% if (caasMode === 'k8s' && tools.indexOf("registry") > -1) { %>
  - name: Ensure <%= appName %> registry
    file:
      path: "{{<%= appName %>_home}}/registry/k8s"
      state: directory
      mode: 0700

  - name: Copy <%= appName %> registry 
    copy:
      src: registry/k8s/{{ item }}
      dest: "{{<%= appName %>_home}}/registry/k8s/{{ item }}"
      mode: 0700
    with_items:
      - registry-pvc.yml
      - registry-daemon.yml
      - registry-rc.yml
      - registry-svc.yml
 
  - name: Launch the Kubernetes registry
    command : "kubectl create -f {{<%= appName %>_home}}/registry/k8s"

  - name: set up a port-forward from our local node to a running Pod
    script : registry/port-forward.sh

  - name: set up a port-forward from our local node to a running Pod
    shell : kubectl port-forward --namespace kube-system $POD 5000:5000 &        
<% } %>

