- hosts: <%= appName %>_managers[0]
  name: "** <%= appName %> images base **"
  gather_facts: false
  become: yes
  become_user: root
  serial: 1
  vars:
    <%= appName %>_home: /opt/<%= appName %>
    manager_ip: <%= defaultIp %>.21
  tasks:

  - name: Configure docker group 
    command : usermod -aG docker vagrant

<% if (ownRegistry) { %>
  - name: Login to docker registry
    command : docker login --username <%= docker_registry_username %> --password <%= docker_registry_password %> <%= docker_registry_server %> 
    no_log: True
<% } %>


